import type React from "react"
import { ClerkProvider } from "@clerk/nextjs"
import "../src/app/globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <head>
          <script
            dangerouslySetInnerHTML={{
              __html: `UPLOADCARE_PUBLIC_KEY = '${process.env.NEXT_PUBLIC_UPLOADCARE_PUBLIC_KEY || ''}';`,
            }}
          />
        </head>
        <body className="h-full overflow-hidden bg-background text-foreground">{children}</body>
      </html>
    </ClerkProvider>
  )
}
